// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Procurement.Migrations
{
    [DbContext(typeof(ProcurementContext))]
    [Migration("20260615062659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Procurement.Models.EmployeeBelonging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeAffiliationOrganizationCode")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EmployeeAffiliationOrganizationName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EmployeeAffiliationUpperOrganizationCode")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EmployeeAffiliationUpperOrganizationName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EmployeeCode")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EmployeeFullName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EmployeeHandJobTitle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EmployeeJobTitleCode")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ReportTargetEmployeeCode")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ReportTargetEmployeeFullName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeBelonging");
                });
#pragma warning restore 612, 618
        }
    }
}
